"""Pydantic data models shared by Echo Core and all verticals."""

from echo.models.compliance import ComplianceResult
from echo.models.affiliate import (
    AffiliateModel,
    AffiliateDestination,
    AffiliateOffer,
    AffiliateOpportunityScore,
    AffiliateService,
    BuyNowSignal,
    DestinationStatus,
    EvidenceStatus,
    EvidenceType,
    OpportunityScoreConfig,
    PriceQuote,
    ProductCandidate,
    ProductEvidence,
    ProductEvidenceConflict,
    ProductSet,
    ProductSetItem,
    ScoreComponent,
    ScoreContribution,
    ScoreFeature,
    ScoreWeight,
)
from echo.models.affiliate_kpi import (
    AffiliateAttribution,
    AffiliateKPIObservation,
    AffiliateKPIMetrics,
)
from echo.models.affiliate_visual import (
    CarouselPlan,
    CarouselSlide,
    ComplianceCheck,
    ComplianceCheckCode,
    ComplianceReport,
    DisclosurePlacement,
    HumanApproval,
    LifestyleScene,
    MarketingClaim,
    PlatformVariant,
    ProductVisualLabel,
    RightsStatus,
    SocialPlatform,
    SocialProposal,
    SlideKind,
    VisualAsset,
    VisualAssetKind,
    VisualPolicy,
)
from echo.models.draft import ContentDraft
from echo.models.enums import (
    ClaimStatus,
    ConflictSeverity,
    ContentType,
    DecisionType,
    FetchStatus,
    PipelineStage,
    ReliabilityTier,
    RejectReason,
    ResearchStatus,
    SourceType,
)
from echo.models.performance import PerformanceSnapshot
from echo.models.publish import PublishedPost
from echo.models.research import (
    ConflictRecord,
    EvidenceItem,
    ResearchClaim,
    ResearchPacket,
    SourceAssessment,
)
from echo.models.review import ReviewDecision
from echo.models.score import OpportunityScore
from echo.models.source import SourceItem
from echo.models.trend import TrendCandidate

__all__ = [
    "AffiliateAttribution",
    "AffiliateDestination",
    "AffiliateModel",
    "AffiliateKPIObservation",
    "AffiliateKPIMetrics",
    "AffiliateOffer",
    "AffiliateOpportunityScore",
    "AffiliateService",
    "BuyNowSignal",
    "CarouselPlan",
    "CarouselSlide",
    "ClaimStatus",
    "ComplianceReport",
    "ComplianceCheck",
    "ComplianceCheckCode",
    "ComplianceResult",
    "ConflictRecord",
    "ConflictSeverity",
    "ContentDraft",
    "ContentType",
    "DecisionType",
    "DestinationStatus",
    "DisclosurePlacement",
    "EvidenceStatus",
    "EvidenceType",
    "EvidenceItem",
    "FetchStatus",
    "OpportunityScore",
    "OpportunityScoreConfig",
    "PerformanceSnapshot",
    "PipelineStage",
    "PublishedPost",
    "ReliabilityTier",
    "RejectReason",
    "ResearchClaim",
    "ResearchPacket",
    "ResearchStatus",
    "ReviewDecision",
    "RightsStatus",
    "ProductCandidate",
    "ProductEvidence",
    "ProductEvidenceConflict",
    "ProductSet",
    "ProductSetItem",
    "PriceQuote",
    "ProductVisualLabel",
    "ScoreComponent",
    "ScoreContribution",
    "ScoreWeight",
    "ScoreFeature",
    "SocialPlatform",
    "SocialProposal",
    "SlideKind",
    "PlatformVariant",
    "LifestyleScene",
    "MarketingClaim",
    "HumanApproval",
    "VisualAsset",
    "VisualAssetKind",
    "VisualPolicy",
    "SourceAssessment",
    "SourceItem",
    "SourceType",
    "TrendCandidate",
]
